GRANT ALL PRIVILEGES ON *.* TO 'jim'@'localhost' IDENTIFIED BY PASSWORD '*A94CCE88FC44D24346E2C8F0F20DB45AF57CAF3A' WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON `jim\_%`.* TO 'jim'@'localhost';

GRANT ALL PRIVILEGES ON `psd_project`.* TO 'jim'@'localhost';